### PR TITLE
Fixed bugs in .params for Phenix; improved documentation

### PR DESCRIPTION
**Pull request by MartinMalyMM**

### CODE REVIEW

**Comment by MartinMalyMM** [comment]
What is wrong with this?

image

**Comment by keitaroyam** [comment]
Not wrong, but you don't need `f""` here. By the way, 
```py
    import sys
    sys.stderr.write("ERROR: moduel GEMMI not found.\n")
    sys.exit(1)
```
could be just written
```py
    raise SystemExit("ERROR: moduel GEMMI not found")
```

**Comment by MartinMalyMM** [comment]
Thanks, I updated the code.

**Comment by keitaroyam** [comment]
You don't need `import sys` either

**Pull request merged**
